### ISSUE TITLE
Unable to set -1 as min value for components

### ISSUE THREAD

**Issue by mufty** [snakewiz/fivem-appearance#11]
I'd like to be able to change the min/max values so that I can have -1 for components meaning I can do a topless guy for example. It seems that changing the values in settings.ts doesn't work as the min value I can enter is still 0 for the components.

This is my components section from the settings.ts:

components: [
    { component_id: 0, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 1, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 2, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 3, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 4, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 5, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 6, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 7, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 8, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 9, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 10, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
    { component_id: 11, drawable: { min: -1, max: 255 }, texture: { min: 0, max: 255 } },
  ],

before someone asks me... yes I did make sure I rebuild the whole thing after these changes :)

**Comment by pedr0fontoura** [comment]
These changes are not supposed to work.

The -1 value for props is just an "alias" for the [ClearPedProp ](https://docs.fivem.net/natives/?_0x0943E5B8E078E76E) native since there's no other way to remove some of the props. For components, you would need to hardcode the "no component" drawable id for each component.

I'll be closing this issue as the described problem is not an actual problem, but you can open another one with a feature request. Also, make sure to give more details about what you want and the drawable id's to create the "aliases".
